### ISSUE TITLE
Utilize OpenWeatherMap's API to return additional weather data

### ISSUE THREAD

**Issue by bmorelli25** [bmorelli25/ReactWeather#1]
Hello [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

Are you interested in ReactJS, RESTful APIs, HTML, Javascript, Webpack, Express, and/or SASS/CSS? Then you've come to the right project!

This issue is pretty open ended as there are so many possible enhancements to be made in terms of data. [OpenWeatherMap](http://openweathermap.org/api) has a ton of great, free features. Currently this weather app utilizes only the current weather data API and returns the current temperature. **[Live Demo](http://still-springs-11020.herokuapp.com/)**

Your task: Utilize OpenWeatherMaps API and return even more great data to the user. Possibilities include: 
- Current wind, rain, clouds, etc.
- Returning an image that changes based on the weather (e.g. a sun when it's hot, a cloud when cloudy, etc.)
- Changing the background based on current weather
- Utilizing the [5 day/3 hour API](http://openweathermap.org/forecast5) to return the 5 day forecast for the searched city
- Any other great ideas you can come up with!

Don't hesitate to reach out with questions, or if you need help understanding the code!

_PS: This project utilizes a `.editorconfig` file. This helps developers define and maintain consistent coding styles between different editors and IDEs. Please ensure your editor is set up to use the `.editorconfig` file. For more information, check out [editorconfig.org](http://editorconfig.org/)._

**Comment by silentiumsi** [comment]
I would like to help out with this one, specifically returning an image (which could also be used as the background) based on the current weather.

**Comment by kopijunkie** [comment]
I'm interested in using the API to get a 5-day forecast for this ticket (& possibly other interesting data to display, once I get stuck in). That's assuming I won't be clashing with what @SimonMckeon will be working on.

**Comment by avi-jain** [comment]
Hullo, I've got an idea too. An additional message (along with the current one which shows temperature) based on the _weather_ parameter returned by the API. Something quirky, like the carrot weather app. Have changed the WeatherMessage to a React Component, and started defining a few of these additional messages. Here's a screen to elaborate -
![sample](https://cloud.githubusercontent.com/assets/16825902/19009707/299bde80-8794-11e6-821e-c761abb2982a.PNG)

**Comment by silentiumsi** [comment]
@kopijunkie There may be a slight breaking change, but I will be putting in a PR pretty soon.

**Comment by kopijunkie** [comment]
@SimonMckeon no worries. it's way past midnight where i am now. so i'll only really get started tomorrow morning after some sleep. :)
