### ISSUE TITLE
Refactor PR #9 code - Background changing based on Weather

### ISSUE THREAD

**Issue by bmorelli25** [bmorelli25/ReactWeather#12]
Hello [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

Are you interested in React JS, Node JS, APIs, HTML, Javascript, Webpack, Express, and/or SASS/CSS? Then you've come to the right project!

This web app allows a user to type in a location, then pulls weather data from [OpenWeatherMap's API](http://openweathermap.org/) and returns it to the user. **[Live Demo](http://still-springs-11020.herokuapp.com/)**

Your task: In #9 @SimonMckeon added in a background changing feature. Based on the current weather conditions, the background of the app will change to match. There is some refactoring that needs to be done to better execute this code. Please see PR #9 for more details on what Simon did. If you'd like to help, comment below, and go for it!

Don't hesitate to reach out with questions, or if you need help understanding the code!

_PS: This project utilizes a `.editorconfig` file. This helps developers define and maintain consistent coding styles between different editors and IDEs. Please ensure your editor is set up to use the `.editorconfig` file. For more information, check out [editorconfig.org](http://editorconfig.org/)._

**Comment by chaintng** [comment]
I will take this :))
