### ISSUE TITLE
Utilize ipinfo.io's API to guess the users location

### ISSUE THREAD

**Issue by bmorelli25** [bmorelli25/ReactWeather#2]
Hello [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

Are you interested in ReactJS, RESTful APIs, HTML, Javascript, Webpack, Express, and/or SASS/CSS? Then you've come to the right project!

This web app allows a user to type in a location, then pulls weather data from [OpenWeatherMap's API](http://openweathermap.org/) and returns it to the user. **[Live Demo](http://still-springs-11020.herokuapp.com/)**

Your task: Utilize [IPinfo.io's API](http://ipinfo.io/) to guess the users current location.

If the location can be determined based on IP address, this information should be displayed in the index header and read something like: "It is x degrees in city"

Don't hesitate to reach out with questions, or if you need help understanding the code!

_PS: This project utilizes a `.editorconfig` file. This helps developers define and maintain consistent coding styles between different editors and IDEs. Please ensure your editor is set up to use the `.editorconfig` file. For more information, check out [editorconfig.org](http://editorconfig.org/)._

**Comment by avi-jain** [comment]
Hello, I'm new to contributions and have done a bit of React. I would like to help out, once I get around the codebase.
Also, why not go with HTML5's geolocation rather than IP based location?

**Comment by bmorelli25** [comment]
Hi avi-jain! Thanks for helping out. I wanted to stay away from HTML5's geolocation because it only works in Chrome v. 50 and above over HTTPS. I'm afraid other browsers may go the same route. With that being said, If you're comfortable with utilizing it and want to implement it in that fashion, that's OK with me!

**Comment by avi-jain** [comment]
While trying to install the dependencies, I get the following error - 
```bash
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (C:\Users\Avi Jain\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Avi Jain\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
```

**Comment by avi-jain** [comment]
While trying to install the dependencies, I get the following error. Any clues as to how to resolve this?

``` bash
$ npm install
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
```

**Comment by bmorelli25** [comment]
What version of node and npm do you have on your machine? 

You can check by running `node -v` and `npm -v`

**Comment by avi-jain** [comment]
npm - 3.10.7 
node - 4.6.0
Never mind though, ran install again and the error disappeared. 
Thanks

**Comment by 93786** [comment]
I'm gonna hope on this train of react questions-
What is the best way to test the app after making changes?
`node server.js`?
Do we need to build the app first to update the bundle.js?

**Comment by bmorelli25** [comment]
Hey @ghwilley ,

You are correct, you must build the app first to see any of your changes. If you open up two commands prompts, you can run `webpack -w` in one. This will watch for any changes and auto update your bundle on every change. Then in your other command prompt run `node server.js` or `npm start`. They are the same thing, and this will run your server. With this setup, changes will be live on localhost:3000 almost instantly (after you refresh the page of course)

**Comment by beatfreaker** [comment]
Hi @bmorelli25 ,

Submitted PR [#20](https://github.com/bmorelli25/React-Weather-App/pull/20) regarding this.

Please check.
