### ISSUE TITLE
Add Google Places autocomplete

### ISSUE THREAD

**Issue by beatfreaker** [bmorelli25/ReactWeather#22]
How about adding google autocomplete in search box to give city suggestions as user type the city name?

**Comment by bmorelli25** [comment]
Yes, yes, and more yes. Great idea @beatfreaker ! Would you like to tackle it?

**Comment by beatfreaker** [comment]
yeah i will give it a try.

**Comment by kundanvishen** [comment]
I am working on it.

**Comment by bmorelli25** [comment]
Hey @beatfreaker - are you still working on this?

**Comment by beatfreaker** [comment]
Hi @bmorelli25 ,

was busy for couple of days, will continue from tomorrow.

**Comment by kundanvishen** [comment]
@beatfreaker Do let me know if you are unable to continue. I would like to work on it.

**Comment by beatfreaker** [comment]
hi @kundansingh1 ,

done with it, will create PR tonight.

**Comment by beatfreaker** [comment]
@bmorelli25 please review [#36](https://github.com/bmorelli25/React-Weather-App/pull/36) PR regarding this issue.

**Comment by bmorelli25** [comment]
Merged #36.
