### ISSUE TITLE
Weather by Zip Code Not Supported

### ISSUE THREAD

**Issue by schmalzs** [bmorelli25/ReactWeather#26]
It doesn't look like the app currently supports retrieving weather by zip code.  Looking at the OpenWeatherMap API, this should be a quick enhancement to make.

**Comment by tetreault** [comment]
@scott-schmalz when that is finished, I can add additional unit tests to tests/api/reactWeatherAppApi.spec.js

**Comment by bmorelli25** [comment]
@scott-schmalz Great idea! Yup, should actually be pretty easy. Check if what was entered was a number, and then if so, append the `zip` parameter instead of the `q` parameter.

**Comment by 93786** [comment]
Is anyone working on this? Otherwise I'll give it a go.

**Comment by schmalzs** [comment]
@ghwilley - I'm taking a look at it now.

**Comment by bmorelli25** [comment]
Hey @scott-schmalz, as you work on this, please take note that openWeatherMap.jsx was just refactored to remove a ton of duplicate code. The new implementation: 

```
module.exports = {
    getWeather: function (key, location) {
        // if key === 'weather' : returns current weather
        // if key === 'forecast' : returns 5 day forecast
        const encodedLocation = encodeURIComponent(location);
        const requestUrl = `${OPEN_WEATHER_MAP_URL}${key}?appid=${API_KEY}&units=${DEFAULT_UNIT}&q=${encodedLocation}`;

        return axios.get(requestUrl).then(function (res) {
            const apiDataHasError = res.data.cod !== '200'
            if (apiDataHasError && res.data.message) { //if true, something went wrong
                throw new Error(res.data.message); //send to error handler in Weather.jsx
            } else {
                return res.data; //send to success case in Weather.jsx
            }
        }, function (res) {
            throw new Error(res.data.message); //if api sends an error, we pull then show to user
        });
    }
};
```

The only effect this should have on what you're doing is that you'll only need to write the code for checking for numbers once, instead of twice :)

**Comment by schmalzs** [comment]
Thanks @bmorelli25 - good to know!  I'll pull this in and merge with it.

I did realize while working this that OpenWeatherMap's API only supports querying by zip code against their `weather` service.  The `forecast` service doesn't support zip code queries.

To get around this, I'm grabbing the city ID off the `weather` response and using that against the `forecast` service.  That'll ensure we're always referencing the same location between the two.  Let me know if that makes sense or if you have any other thoughts.  Thanks!

**Comment by schmalzs** [comment]
^ scratch that...In the documentation for `forecast` ([http://openweathermap.org/forecast5](http://openweathermap.org/forecast5)), I didn't see any mention of zip code querying support...but I just ran a test and it works...  so that makes it even easier.
