### ISSUE TITLE
CSS / SASS Site Re-design (With or without Foundation)

### ISSUE THREAD

**Issue by bmorelli25** [bmorelli25/ReactWeather#3]
Hello [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

Are you interested in SASS/CSS and Reactjs? Then you've come to the right project!

This web app allows a user to type in a location, then pulls weather data from OpenWeatherMap's API and returns it to the user. **[Live Demo](http://still-springs-11020.herokuapp.com/)**

Your task: A complete site redesign. Currently the web app utilizes [Foundation](http://foundation.zurb.com/) for styling. Feel free to stick with Foundation, or go you're own route. I'm not looking for anything crazy here, but if you can help me make the site look more aesthetically pleasing, I'd greatly appreciate it!

Please feel free to reach out with any questions you have about the code/project - I'm more than willing to help!

_PS: This project utilizes a `.editorconfig` file. This helps developers define and maintain consistent coding styles between different editors and IDEs. Please ensure your editor is set up to use the `.editorconfig` file. For more information, check out [editorconfig.org](http://editorconfig.org/)._

**Comment by lungyiing** [comment]
I'd like to have a crack at this over the weekend. I feel like sticking with the current minimal look is good perhaps just simple white text with the location, weather and temperature and a stock photo w/ the relevant weather condition.

**Comment by bmorelli25** [comment]
Hey Chris! Thanks for offering to help. 

I agree, minimalist is best. Let me know if you need any help or have any questions on the codebase/react as you go.

Thanks again!

**Comment by geoffdavis92** [comment]
@bmorelli25 I am interested in contributing as well. I have a few questions:
1. Do you have any plans to add weather visualization (ie clouds for cloudy, sun for clear skies, etc)?
2. Are you taking anyone's design and running with it or do you have an idea/wireframes or initial sketches to go off of?

**Comment by bmorelli25** [comment]
Hey @geoffdavis92 ! Please do!
1. Yes, yes, more yes. I would love to see weather visualization implemented. 
2. No wire frames to go off of. Really from this 'issue' I was looking for two things: general website layout (nav bar styling, links, text color), and the weather visualizations.

My main hope, and what I think would be really cool is to have a unique background color based off the current weather. Something similar to what these two apps do: [ex: 1](https://s-media-cache-ak0.pinimg.com/564x/37/43/b0/3743b0bb07a48f4cb002024669a7fbc2.jpg), [ex: 2](https://mir-s3-cdn-cf.behance.net/project_modules/disp/1420808455691.560bda7775034.png). There are a [bunch of great, free, white .pngs](https://www.google.com/search?biw=1557&bih=811&tbm=isch&sa=1&q=white+weather+png&oq=white+weather+png&gs_l=img.3..0i8i7i30k1.4029.4694.0.4795.6.6.0.0.0.0.138.308.2j1.3.0....0...1c.1.64.img..4.2.218.L-d4y0G8wJ8) that could be used on a color changing background based off the weather as well.

I wanted to leave it somewhat opened ended to encourage people to contribute in whatever way they are best able to.

**Comment by lungyiing** [comment]
@bmorelli25 #16 is an implementation of this if you want to take a look.
