### ISSUE TITLE
CSS / SASS Re-design - REACT

### ISSUE THREAD

**Issue by bmorelli25** [bmorelli25/ReactWeather#39]
Hello [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

Are you interested in SASS/CSS and Reactjs? Then you've come to the right project!

This web app allows a user to type in a location, then pulls weather data from OpenWeatherMap's API and returns it to the user. **[Live Demo](http://still-springs-11020.herokuapp.com/)** Please note the live demo is an old version of the site. Download and run it to see the updated version.

Your task: Make it look prettier! Currently on weather load, a background image is displayed to the user. It tiles and looks pretty dated. Maybe a solid color would be better? You tell me. Lets discuss your ideas and go from there. I think simpler and cleaner is better. 

Please feel free to reach out with any questions you have about the code/project - I'm more than willing to help!

_PS: This project utilizes a `.editorconfig` file. This helps developers define and maintain consistent coding styles between different editors and IDEs. Please ensure your editor is set up to use the `.editorconfig` file. For more information, check out [editorconfig.org](http://editorconfig.org/)._

**Comment by code4cake** [comment]
Hey man is this still open? Can I pick it up?

**Comment by bmorelli25** [comment]
Hi @dantesolis  - I've already got #42 open on this issue. Haven't had a chance to look over it yet, but at first glance it appears it will solve this issue. Please feel free to open up a new issue if you have other contributions you want to make

**Comment by code4cake** [comment]
@bmorelli25 thanks. I'll fork and download the project. Are there any other "pressing" open issues, you would like  tackled?
