### ISSUE TITLE
Turn API Key into an Environment Variable (process.env.API_KEY)

### ISSUE THREAD

**Issue by bmorelli25** [bmorelli25/ReactWeather#4]
Hello [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

Are you interested in React JS, Node JS, APIs, HTML, Javascript, Webpack, Express, and/or SASS/CSS? Then you've come to the right project!

This web app allows a user to type in a location, then pulls weather data from [OpenWeatherMap's API](http://openweathermap.org/) and returns it to the user. **[Live Demo](http://still-springs-11020.herokuapp.com/)**

Your task: Implement an enviornment variable for the Open Weather Map `API_KEY`. Currently the API Key is just sitting in the URL, visible for all to see. This is obviously not a best practice. Update `openWeatherMap.jsx` to utilize the new enviornment variable named `API_KEY`. Also update the `Readme` to explain how to use the environment variable.

Don't hesitate to reach out with questions, or if you need help understanding the code!

_PS: This project utilizes a `.editorconfig` file. This helps developers define and maintain consistent coding styles between different editors and IDEs. Please ensure your editor is set up to use the `.editorconfig` file. For more information, check out [editorconfig.org](http://editorconfig.org/)._

**Comment by darrylpargeter** [comment]
Hey, 

I would like to this one ago if possible?

**Comment by bmorelli25** [comment]
Hey Darryl, I appreciate your offer... about 3 seconds (literally) before you posted this, someone opened a pull request for this fix. 

Feel free to take a look at the codebase for this project. If there is anything else you'd like to contribute or change, feel free to look at the open issues, or create a new one!

**Comment by brendanbowidas** [comment]
Commenting for assignment

**Comment by bmorelli25** [comment]
Done. merged and closed
