### ISSUE TITLE
Current Location Temp in Nav Not Tied into Temperature Type

### ISSUE THREAD

**Issue by schmalzs** [bmorelli25/ReactWeather#53]
The temperature of your current location in the nav bar is not tied into the temperature type toggle.  All other temps can be toggled between degrees F and degrees C, however, the current location temperature in the nav will always remain in degrees F.

**Comment by andrewwylde** [comment]
I think I can grab this one, @bmorelli25 . Just want to verify that it's still a desired feature!

Current strategy would be to add `tempType`'s state to the `Main` component, and pass that and an `updateTempType` to the child views so we can trigger re-renders accordingly.
