### ISSUE TITLE
Write React / API / JS Tests!

### ISSUE THREAD

**Issue by bmorelli25** [bmorelli25/ReactWeather#6]
Hello [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

Are you interested in React JS, Node JS, APIs, HTML, Javascript, Webpack, Express, and/or SASS/CSS? Then you've come to the right project!

This web app allows a user to type in a location, then pulls weather data from [OpenWeatherMap's API](http://openweathermap.org/) and returns it to the user. **[Live Demo](http://still-springs-11020.herokuapp.com/)**

Your task: Before we can write any tests, this application needs a testing foundation!

Don't hesitate to reach out with questions, or if you need help understanding the code!

_PS: This project utilizes a `.editorconfig` file. This helps developers define and maintain consistent coding styles between different editors and IDEs. Please ensure your editor is set up to use the `.editorconfig` file. For more information, check out [editorconfig.org](http://editorconfig.org/)._

**Comment by silentiumsi** [comment]
I am currently creating the testing foundation using Mocha, Chai and Enzyme.

**Comment by bmorelli25** [comment]
Awesome, thanks @SimonMckeon ! I'll assign you to this issue. Anyone else who wants to add tests is still welcome to, just please wait until Simon has created his pull request so we ensure all tests are written uniformly.

**Comment by SimonMckeon** [comment]
PR created!

**Comment by bmorelli25** [comment]
Testing foundation has been created and merged (#7). Anyone who wants to write tests can feel free to now. I'm going to close this issue and create a new one for the tests.
